<?php View::content() ?>
<?php echo Form::open('usuario/crearadministrador?rol=3') ?>
<h1>Informacion General</h1>
<div class="form-group">
	<label>Usuario:</label>
	<?php echo Form::text("usuario.usuario","class='form-control required'") ?>
</div>
<div class="form-group">
	<label>Contraseña</label>
	<?php echo Form::pass("usuario.contrasenia","class='form-control required'",'') ?>
	<label>Repetir Contraseña</label>
	<?php echo Form::pass("usuario.re_contrasenia","class='form-control required'",'') ?>
</div>
<div class="form-group">
	<label>Nombres</label>
	<?php echo Form::text("usuario.nombres","class='form-control' placeholder='Nombres...'") ?>
</div>
<div class="form-group"> 
	<label>Apellidos</label>
	<?php echo Form::text("usuario.apellidos","class='form-control' required placeholder='Apellidos...'") ?>
</div>
<div class="form-group">
	<label>Aparición en los Reportes:</label>
	<?php echo Form::text("usuario.aparicion","class='form-control' placeholder='Aparición en los Reportes...'") ?>
</div>
<h1>Datos Personales</h1>
<div class="form-group">
	<label>Genero</label>
	<div class="check">
		<label>
		<?php echo Form::radio("usuario.genero",'F',null,'1') ?> Femenino
		</label>
		<label>
		<?php echo Form::radio("usuario.genero",'M',null) ?> Masculino
		</label>
	</div>
</div>
<div class="form-group">
	<label>Fecha de Nacimiento</label>
	<?php echo Form::text("usuario.nacimiento","class='form-control datepicker' placeholder='Nacimiento...'") ?>
</div>
<div class="form-group">
	<label>Correo</label>
	<?php echo Form::text("usuario.email","class='form-control' placeholder='Correo...'") ?>
</div>
<div class="form-group">
	<label>Telefono</label>
	<?php echo Form::text("usuario.telefono","class='form-control' placeholder='Telefono...'") ?>
</div>
<div class="form-group">
	<label>Celular</label>
	<?php echo Form::text("usuario.celular","class='form-control' placeholder='Celular...'") ?>
</div>
<div class="form-group">
	<label>Pais</label>
      <select name="usuario[pais]" id="" class="form-control">
      	<?php foreach ($countries as $key => $value): ?>
      		<option value="<?php echo $value ?>"><?php echo $value ?></option>
      	<?php endforeach ?>
      </select>
</div>
<div class="form-group">
	<label>Ciudad</label>
	<?php echo Form::text("usuario.ciudad","class='form-control' placeholder='Ciudad...'") ?>
</div>
<div class="form-group">
	<label>DNI</label>
	<?php echo Form::text("usuario.dni","class='form-control' placeholder='DNI...'") ?>
</div>
<div class="form-group">
	<label>Colegiatura / Licencia</label>
	<?php echo Form::text("usuario.colegiatura","class='form-control' placeholder='Colegiatura...'") ?>
</div>
<?php if (Input::hasget('rol')): ?>
	<?php echo Form::hidden("usuario.role",null,Input::get('rol')) ?>
<?php else: ?>
	<?php echo Form::hidden("usuario.role",null,7) ?>
<?php endif ?>

<?php echo Form::submit("Crear","class='btn btn-default'") ?>
<?php echo Html::link("equipo/crear","Cancelar",'class="btn btn-default"') ?>
<?php echo Form::close() ?>
<br>
<br>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/jquery-ui.css">

<style type="text/css">
	.ui-datepicker-month,.ui-datepicker-year{
		color: black;
	}
</style>