<?php View::content() ?>
<br>
<h1>Subida de Archivo</h1>
<?php echo Form::openMultipart() ?>
<div class="form-group">
	<label>Nombre de Plantilla</label>
	<?php echo Form::text("nombre","class='form-control' required",isset($plantilla->nombre) ? $plantilla->nombre : null) ?>
</div>
<div class="form-group">
	<label for=""> Ingrese un archivo .docx:</label>
	<?php echo Form::hidden("id",null,isset($plantilla->id) ? $plantilla->id : null) ?>
	<?php echo Form::file('archivo',"required") ?>
   	<?php echo Form::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
</div>
    <?php echo Form::submit('subir',"class='btn btn-default'") ?>
<?php echo Form::close() ?>
<br/>



<!--<script type="text/javascript" src="<?php /*echo PUBLIC_PATH */?>ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="<?php /*echo PUBLIC_PATH*/ ?>ckeditor/config.js"></script>
	<script type="text/javascript" src="<?php/* echo PUBLIC_PATH*/ ?>ckeditor/styles.js"></script>
	<script type="text/javascript">
/**
 * Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/* exported initSample */

if ( CKEDITOR.env.ie && CKEDITOR.env.version < 9 )
	CKEDITOR.tools.enableHtml5Elements( document );

// The trick to keep the editor in the sample quite small
// unless user specified own height.
CKEDITOR.config.height = 500;
CKEDITOR.config.width = 'auto';

var initSample = ( function() {
	var wysiwygareaAvailable = isWysiwygareaAvailable(),
		isBBCodeBuiltIn = !!CKEDITOR.plugins.get( 'bbcode' );

	return function() {
		var editorElement = CKEDITOR.document.getById( 'editor' );

		// :(((
		if ( isBBCodeBuiltIn ) {
			editorElement.setHtml(
				'Hello world!\n\n' +
				'I\'m an instance of [url=http://ckeditor.com]CKEditor[/url].'
			);
		}

		// Depending on the wysiwygare plugin availability initialize classic or inline editor.
		if ( wysiwygareaAvailable ) {
			CKEDITOR.replace( 'editor' );
		} else {
			editorElement.setAttribute( 'contenteditable', 'true' );
			CKEDITOR.inline( 'editor' );

			// TODO we can consider displaying some info box that
			// without wysiwygarea the classic editor may not work.
		}
	};

	function isWysiwygareaAvailable() {
		// If in development mode, then the wysiwygarea must be available.
		// Split REV into two strings so builder does not replace it :D.
		if ( CKEDITOR.revision == ( '%RE' + 'V%' ) ) {
			return true;
		}

		return !!CKEDITOR.plugins.get( 'wysiwygarea' );
	}
} )();


	</script>-->
	<!-- <link rel="stylesheet" href="contents.css">
<?php// echo Form::open() ?>
<div class="form-group">
	<label for="">Nombre:</label>
	<?php //echo Form::text("nombre","class='form-control'") ?>
</div>
<textarea name="editor" class='ckeditor' id="editor" cols="30" rows="10"></textarea>
<br>
<?php //echo Form::submit('Guardar','class="btn btn-default"') ?>
<?php //echo Form::close() ?> -->
<br><br>
