<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title><?php echo $titulo ?></title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css("bootstrap/css/bootstrap.min") ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("jquery/jquery.min") ?>
  <?php echo Tag::js("jquery/jquery.kumbiaphp") ?>
  <?php echo Tag::js("bootstrap/js/bootstrap.min") ?>
</head>
<body>

  <style type="text/css">
    body{
      background-image: url('../img/fondo_auth.jpg');
      background-size: 100%;
    }
  </style>

  <?php View::content(); ?>

</body>
</html>
