<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $titulo ?></title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo PUBLIC_PATH ?>bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo PUBLIC_PATH ?>bower_components/metisMenu/dist/metisMenu.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo PUBLIC_PATH ?>dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo PUBLIC_PATH ?>bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <?php echo Tag::css('jquery-ui') ?>
    <?= Html::includeCss() ?>
    <style type="text/css">
        #side-menu a{
            background-color: #21405f;
            color:white;
        }
    </style>
      <script src="<?php echo PUBLIC_PATH ?>bower_components/jquery/dist/jquery.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" style="margin-top: 20px" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <?php echo Html::link("auth/index","Logo",'class="navbar-brand"') ?>
      <form class="navbar-form navbar-left" role="search">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Búsqueda">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
      </span>
    </div><!-- /input-group -->
      </form>
            </div>
            <!-- /.navbar-header -->
        
            <ul class="nav navbar-top-links navbar-right">
                <?php if (Auth::is_valid()): ?>
                    <li>
                        <a href="#"><?php echo Auth::get("usuario") ?></a>
                    </li>
                    <li>
                        <?php echo Html::link("auth/logout","Logout") ?>
                    </li>
                <?php else: ?>
                    <li>
                        <?php echo Html::link("usuarios/crear","Nuevo Usuario") ?>
                    </li>  
                    <li>
                        <?php echo Html::link("auth/login","Login") ?>
                    </li>                   
                <?php endif ?>
            <!--
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages 
                </li>
                <!-- /.dropdown 
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks 
                </li>
                <!-- /.dropdown 
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts 
                </li>
                <!-- /.dropdown 
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>

                    <!-- /.dropdown-user 
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <?php echo Html::link("index/","Inicio") ?>
                        </li>
                        <li>
                            <?php echo Html::link("usuario/pass/","Cambiar password") ?>
                        </li>
                        <li>
                            <?php echo Html::link("index/perfilpersonal","Perfil Personal") ?>
                        </li>
                        <?php if (Auth::is_valid() and Auth::get('rol')<3): ?>
                            
                        
                        <li>
                            <a href="#">Administración<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <?php echo Html::link("usuario/listareditores?rol=2",'Editores') ?>
                                </li>
                                <li>
                                    <?php echo Html::link("plan/",'Planes') ?>
                                </li>
                                <li>
                                    <?php echo Html::link("equipo/",'Equipos') ?>
                                </li>
                                <li>
                                    <?php echo Html::link("plantilla/",'Formularios y Plantillas') ?>
                                </li>
                                <li>
                                    <a href="<?php echo PUBLIC_PATH ?>plan/byequipo">Plan Contratado</a>
                                </li>
                                <li>
                                    <a href="#">Facturación</a>
                                </li>
                                <li>
                                    <?php echo Html::link("codigo/","Codigos de Api") ?>
                                </li>
                                <li>
                                    <?php echo Html::link("equipo/usuarios",'Usuarios de Equipo') ?>
                                </li>
                                <li>
                                    <?php echo Html::link("usuario/crear","Crear Usuario") ?>
                                </li>
                                <li>
                                    <?php echo Html::link("usuario/listar","Modificar Usuario") ?>
                                </li>
                               <!--  <li>
                                    <?php /*echo Html::link("usuario/listareliminar","Eliminar Usuario") */?>
                                </li> -->
                                <li>
                                    <?php echo Html::link("formulario/","Formularios") ?>
                                </li>
                                <li>
                                    <?php echo Html::link("plantilla/","Plantillas") ?>
                                </li>
                                <li>
                                    <?php echo Html::link("intervenciones/lista","Lista de Intervenciones") ?>
                                </li>
                                <li>
                                    <?php echo Html::link("estadisticas/generales","Estadísticas Generales") ?>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <?php endif ?>
                        <li>
                            <a href="tables"><span class="fa arrow"></span> Intervenciones</a>
                            <ul class="nav nav-second-level">
                            <?php 
                            $rol = Load::model("usuario")->getRol();

                             ?>
                             <?php if ((int)$rol >= 1  and  (int)$rol <= 5): ?>
                                 
                                <li>
                                    <?php echo Html::link("intervenciones/lista",'Lista') ?>
                                </li>
                             <?php endif ?>
                                <li>
                                    <?php echo Html::link("intervenciones/nuevo",'Nuevo Registro') ?>
                                </li>
                               <!--  <li>
                                    <?php// echo Html::link('intervenciones/','Consultar Registro') ?>
                                </li> -->
                            <?php if ((int)$rol >= 1  and  (int)$rol <= 3): ?>
                                 <li>
                                    <?php echo Html::link('intervenciones/busqueda',"Busqueda") ?>
                                </li>
                                <li>
                                    <?php echo Html::link('estadisticas/generales',"Estadísticas Generales") ?>
                                </li>
                             <?php endif ?>
                                
                               <!--  <li>
                                    <a href="flot">Exportar Registros</a>
                                </li>  -->                                  
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="forms">Soporte Técnico</a>
                        </li>
                        <li>
                            <a href="<?php echo PUBLIC_PATH ?>auth/logout">Cerrar Sesión</a>
                        </li>
                     
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
        <br>
            <?php View::partial('breadcrumb') ?>

            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 style="margin-top:0px"><?php echo $titulo ?></h1>
                        <hr>
                        <?php View::content() ?>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
  
<?php echo Tag::js('jquery/jquery.kumbiaphp') ?>
<?php echo Tag::js('jquery/jquery-ui.min') ?>
<script type="text/javascript">
    $(document).ready(function(){
        $.datepicker.regional['es'] = {
         closeText: 'Cerrar',
         prevText: '<Ant',
         nextText: 'Sig>',
         currentText: 'Hoy',
         monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
         dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
         dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
         dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
         weekHeader: 'Sm',
         dateFormat: 'dd/mm/yy',
         firstDay: 1,
         isRTL: false,
         showMonthAfterYear: false,
         yearSuffix: ''
         };
         $.datepicker.setDefaults($.datepicker.regional['es']);
        $(".datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat:'yy-mm-dd'
        });
    })
</script>

    
    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>dist/js/sb-admin-2.js"></script>

</body>

</html>
